### ISSUE TITLE
Wrong strlen for utf-8

### ISSUE THREAD

**Issue by nehxby** [dimikot/db_type#1]
When db_pgsql_type used for save not-latin strings, strlen work incorrect.

Неправильно работает определение длины строки для UTF-8 строк с кириллицей. У себя исправил изменением вызова mb_strlen() вместо strlen() в String.php и Length.php.

Пока не вижу где можно файлик прикрепить. Если найду, добавлю файл патча

**Comment by dimikot** [comment]
Не факт, что это баг. Библиотека не знает (и не может знать), используется ли в скрипте модуль mbstring (или он просто так подключен, а на самом деле не используется).

Правильно работать с режимом mbstring.func_overload = 7 в php.ini. Тогда strlen начинает работать правильно с UTF-8, и библиотека тоже работает корректно.

**Comment by nehxby** [comment]
Ок, спасибо за информацию по php.ini.
